export const GET_RECORDS = 'GET_RECORDS';
export const GET_RECORD = 'GET_RECORD';
export const ADD_RECORD = 'ADD_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
export const RESET_EDIT_MODE = 'RESET_EDIT_MODE';
export const CLEAR_CURRENT_RECORD = 'CLEAR_CURRENT_RECORD';
